name: TimeTracker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  dio: ^3.0.10
  flutter_audio_recorder: ^0.5.5
  shared_preferences: ^0.5.10
  fluttertoast: ^7.1.0
  path_provider: ^1.6.14
  audioplayers: ^0.16.1
  connectivity: ^0.4.9+2
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat Black
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: Montserrat BlackItalic
      fonts:
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat BoldItalic
      fonts:
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
    - family: Montserrat ExtraBold
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: Montserrat ExtraLight
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
    - family: Montserrat Italic
      fonts:
        - asset: assets/fonts/Montserrat-Italic.ttf
    - family: Montserrat Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Montserrat LightItalic
      fonts:
        - asset: assets/fonts/Montserrat-LightItalic.ttf
    - family: Montserrat Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat MediumItalic
      fonts:
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat SemiBoldItalic
      fonts:
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
    - family: Montserrat Thin
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
    - family: Montserrat ThinItalic
      fonts:
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
